#!/usr/bin/env python3


import numpy as np


def combineFiles(effFiles,outputFile):

    newData = []
    nf = 0
    for effFile in effFiles:
        effData = np.genfromtxt(effFile,names=True,
                                case_sensitive='lower',
                                skip_header=2,delimiter=';')        
        nf += 1

        newData.append(effData)

    newData = np.array(newData,dtype=effData.dtype)
    np.savetxt(outputFile,newData,delimiter=',',header=','.join(newData.dtype.names),fmt='%1.3e')


if __name__ == "__main__":

    import argparse
    ap = argparse.ArgumentParser(description=
            "Merge individual csv datas generated by getEffsFromROOT.py or getEffsFromFolder.py.")
    ap.add_argument('-f', '--inputFiles', required=True,nargs='+',
            help='list of csv files to be merged', default =[])

    ap.add_argument('-o', '--outputFile', required=False, help='output file [atlas_susy_2018_19_effs.csv].',
                    default='atlas_susy_2018_19_effs.csv')


    args = ap.parse_args()
    inputFiles = args.inputFiles
    outputFile = args.outputFile

    combineFiles(inputFiles,outputFile)







