#!/usr/bin/env python3


import numpy as np
import json

def combineFiles(effFiles,outputFile):

    combinedData = list()
    for effFile in effFiles:
        with open(effFile,'r') as f:
            combinedData.append(json.load(f))

    with open(outputFile,'w') as f:
        json.dump(combinedData,f,indent=4)

if __name__ == "__main__":

    import argparse
    ap = argparse.ArgumentParser(description=
            "Merge individual json files generated by getEffsFromROOT.py or getEffsFromFolder.py.")
    ap.add_argument('-f', '--inputFiles', required=True,nargs='+',
            help='list of json files to be merged', default =[])

    ap.add_argument('-o', '--outputFile', required=False, help='output file [atlas_susy_2018_19_effs.json].',
                    default='atlas_susy_2018_19_effs.json')


    args = ap.parse_args()
    inputFiles = args.inputFiles
    outputFile = args.outputFile

    combineFiles(inputFiles,outputFile)







