[options]
cleanOutput = False
runMadGraph = True
runPythia=True
runDelphes = True
ncpu = 1
ncore = 6
[AuxPars]
#massTauPairs = $loop{[(100.0, 0.2), (200.0, 0.2), (300.0, 0.2), (400.0, 0.2), (500.0, 0.2), (600.0, 0.2), (700.0, 0.2), (800.0, 0.2), (900.0, 0.2), (1000.0, 0.2), (100.0, 1.0), (200.0, 1.0), (300.0, 1.0), (400.0, 1.0), (500.0, 1.0), (600.0, 1.0), (700.0, 1.0), (800.0, 1.0), (900.0, 1.0), (1000.0, 1.0), (100.0, 4.0), (200.0, 4.0), (300.0, 4.0), (400.0, 4.0), (500.0, 4.0), (600.0, 4.0), (700.0, 4.0), (800.0, 4.0), (900.0, 4.0), (1000.0, 4.0), (100.0, 10.0), (200.0, 10.0), (300.0, 10.0), (400.0, 10.0), (500.0, 10.0), (600.0, 10.0), (700.0, 10.0), (800.0, 10.0), (900.0, 10.0), (1000.0, 10.0)]}
mLLP = $loop{[500.]}
#tauns = $loop{[0.01,0.025,0.05,0.1,0.5,1.0,5.0,10.0]}
tauns = 0.1
[DelphesPars]
delphesDir = DelphesLLP
delphescard = Cards/delphes_card_chargino.dat
[MadGraphPars]
#MG5 Cards:
proccard = Cards/proc_card_mg5_pp2chgn1.dat # Optional (only used if processFolder does not exist)
paramcard = Cards/wino_600GeV_0p2ns.dat # Path to the default parameter_card.dat to be used by MadGraph. Note that the parameter values defined in the MadGraphSet section below will automatically overwrite the values in paramcard. If not defined, the default file for the model will be used.
runcard = Cards/run_card_bias.dat # Path to the default run_card.dat to be used by MadGraph. Note that the parameter values defined in the MadGraphSet section below will automatically overwrite the values in runcard. If not defined, the default file for the model will be used.
pythia8card = Cards/pythia8_card.dat
delphescard = Cards/delphes_card_chargino.dat
processFolder = ./pp2chgn1_test
[MadGraphSet]
iseed = ${MadGraphPars:runNumber}
nevents = 50000
mch1 = ${AuxPars:mLLP}
wch1 = 6.582119569e-16/(${AuxPars:tauns})
mneu1 = ${mch1}-0.160
xqcut = ${mch1}/10
time_of_flight = 0.01
pt_bias_target = $loop{[1000.0,5000.0]}
pt_bias_enhancement_power = 4.0
pt_bias_min = 50.0
run_tag = "wino_%1.0fGeV_%1.3fns" %(${mch1},${AuxPars:tauns})
